     
for bandit_box = 1:params.n_bandits
    this_location = [params.ranking_x_border_box + bandit_box * (params.ranking_box_size + params.ranking_x_border_box),...
                     params.ranking_ypos];
    Screen('FrameRect',w,params.ranking_color,[this_location(1) - params.ranking_box_size/2,...
                                               this_location(2) - params.ranking_box_size/2,...
                                               this_location(1) + params.ranking_box_size/2,...
                                               this_location(2) + params.ranking_box_size/2],...
                                               params.ranking_pen);
end

clear bandit_box this_location