for b = 1:params.n_bandits
    Screen('DrawTexture',...
                w,...
                img_textures{data.ranking_bandits_shape(b)},...
                [],...
                [data.ranking_bandits_final_x(b) - params.stim_size_ranking/2,...
                 data.ranking_bandits_final_y(b) - params.stim_size_ranking/2,...
                 data.ranking_bandits_final_x(b) + params.stim_size_ranking/2,...
                 data.ranking_bandits_final_y(b) + params.stim_size_ranking/2]...
                );
    
end

clear b