Screen('FillRect', w, ...
                [255,255,255],...
                [button_x_pos - params.stim_size_button/2,...
                 button_y_pos - params.stim_size_button/2,...
                 button_x_pos + params.stim_size_button/2,...
                 button_y_pos + params.stim_size_button/2]);