Screen('DrawTexture',w,img_textures{data.estimation_shape(trial_est)},...
                [],...
                [params.stim_midpoint(1) - params.stim_size_estimation/2,...
                 params.stim_midpoint(2) - params.stim_size_estimation/2,...
                 params.stim_midpoint(1) + params.stim_size_estimation/2,...
                 params.stim_midpoint(2) + params.stim_size_estimation/2]...
                );