Screen('DrawTexture',w,img_textures{data.bandit_right_shape(trial)},...
                [],...
                [params.stim_pos_right(1) - params.stim_size/2,...
                 params.stim_pos_right(2) - params.stim_size/2,...
                 params.stim_pos_right(1) + params.stim_size/2,...
                 params.stim_pos_right(2) + params.stim_size/2]...
                );  